/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab1.pkg1;

import  javax.swing.table.DefaultTableModel;
import  javax.swing.JOptionPane;
import java.util.ArrayList;
import javax.swing.JFileChooser;
import java.io.File;
import java.io.FileWriter;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.ObjectOutputStream;
import java.io.ObjectInputStream;
import java.io.FileOutputStream;
import java.io.FileInputStream;
import java.net.DatagramSocket;
import java.net.DatagramPacket;
import java.net.InetSocketAddress;
import javax.swing.SwingUtilities;
import java.util.List;



/**
 *
 * @author student
 */
public class NewJFrame extends javax.swing.JFrame {
    
DatagramSocket serverSocket;
DatagramSocket resultSocket;
List<InetSocketAddress> clients = new ArrayList<>();
List<Double> partialResults = new ArrayList<>();
int expectedParts = 0;
int currentRow = -1;

    ArrayList<RecIntegral> arrInteg = new ArrayList<>();

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
        startServer();   
    }
  private void startServer() {
    // Поток для HELLO
    new Thread(() -> {
        try {
            serverSocket = new DatagramSocket(5000);
            byte[] buf = new byte[1024];
            DatagramPacket packet = new DatagramPacket(buf, buf.length);

            while (true) {
                serverSocket.receive(packet);
                String msg = new String(packet.getData(), 0, packet.getLength());

                if (msg.equals("HELLO")) {
                    InetSocketAddress addr = new InetSocketAddress(packet.getAddress(), packet.getPort());
                    clients.add(addr);

                    SwingUtilities.invokeLater(() ->
                        JOptionPane.showMessageDialog(this, "Клиент подключён: " + addr)
                    );
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }).start();

    // Поток для результатов
    new Thread(() -> {
        try {
            resultSocket = new DatagramSocket(5001);

            while (true) {
                byte[] buf = new byte[1024];
                DatagramPacket p = new DatagramPacket(buf, buf.length);
                resultSocket.receive(p);

                String msg = new String(p.getData(), 0, p.getLength());
                String[] parts = msg.split(" ");

                double value = Double.parseDouble(parts[1]);

                synchronized (this) {
                    partialResults.add(value);

                    if (partialResults.size() == expectedParts) {
                        double total = partialResults.stream().mapToDouble(Double::doubleValue).sum();
                        partialResults.clear();

                        SwingUtilities.invokeLater(() -> {
                            DefaultTableModel t = (DefaultTableModel) jTable1.getModel();
                            t.setValueAt(total, currentRow, 3);
                        });
                    }
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }).start();
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButtonAdd = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();
        jButtonResult = new javax.swing.JButton();
        jTextFieldLow = new javax.swing.JTextField();
        jTextFieldUp = new javax.swing.JTextField();
        jTextFieldStep = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        AddColection = new javax.swing.JButton();
        DeleteAll = new javax.swing.JButton();
        SaveText = new javax.swing.JButton();
        SaveBinary = new javax.swing.JButton();
        DownloadBinary = new javax.swing.JButton();
        DownloadText = new javax.swing.JButton();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 153, 0));
        setBounds(new java.awt.Rectangle(0, 0, 10, 10));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(new java.awt.Color(255, 255, 255));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                formComponentHidden(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setForeground(new java.awt.Color(204, 0, 51));

        jScrollPane1.setForeground(new java.awt.Color(255, 0, 102));

        jTable1.setBackground(new java.awt.Color(204, 204, 204));
        jTable1.setBorder(new javax.swing.border.MatteBorder(null));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Нижний порог", "Верхний порог", "Шаг", "Результат"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButtonAdd.setBackground(new java.awt.Color(204, 204, 204));
        jButtonAdd.setText("Добавить");
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });

        jButtonDelete.setBackground(new java.awt.Color(204, 204, 204));
        jButtonDelete.setText("Удалить");
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });

        jButtonResult.setBackground(new java.awt.Color(204, 204, 204));
        jButtonResult.setText("Рассчитать");
        jButtonResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResultActionPerformed(evt);
            }
        });

        jLabel1.setText("Нижний порог");

        jLabel2.setText("Верхний порог");

        jLabel3.setText("Шаг");

        jLabel4.setText("1/x");

        AddColection.setBackground(new java.awt.Color(204, 204, 204));
        AddColection.setText("Заполнить");
        AddColection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddColectionActionPerformed(evt);
            }
        });

        DeleteAll.setBackground(new java.awt.Color(204, 204, 204));
        DeleteAll.setText("Очистить");
        DeleteAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteAllActionPerformed(evt);
            }
        });

        SaveText.setBackground(new java.awt.Color(204, 204, 204));
        SaveText.setText("Сохр. текст");
        SaveText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveTextActionPerformed(evt);
            }
        });

        SaveBinary.setBackground(new java.awt.Color(204, 204, 204));
        SaveBinary.setText("Сохр. двоичный");
        SaveBinary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveBinaryActionPerformed(evt);
            }
        });

        DownloadBinary.setBackground(new java.awt.Color(204, 204, 204));
        DownloadBinary.setText("Загр. двоичный");
        DownloadBinary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DownloadBinaryActionPerformed(evt);
            }
        });

        DownloadText.setBackground(new java.awt.Color(204, 204, 204));
        DownloadText.setText("Загр. текст");
        DownloadText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DownloadTextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(243, 243, 243)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(DownloadBinary, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SaveBinary, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(DownloadText, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SaveText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonResult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AddColection, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DeleteAll, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 50, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap(78, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1)
                        .addComponent(jLabel3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldUp, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldStep, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldLow, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel2))
                    .addGap(328, 328, 328)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(23, 23, 23)
                .addComponent(jButtonAdd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SaveText)
                    .addComponent(jButtonDelete))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SaveBinary)
                    .addComponent(jButtonResult))
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DownloadText)
                    .addComponent(AddColection))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DeleteAll)
                    .addComponent(DownloadBinary))
                .addGap(65, 65, 65)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(68, 68, 68)
                    .addComponent(jLabel1)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jTextFieldLow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jLabel2)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jTextFieldUp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jLabel3)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jTextFieldStep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(284, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 5, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
if (jTextFieldLow.getText().isEmpty() ||
        jTextFieldUp.getText().isEmpty() ||
        jTextFieldStep.getText().isEmpty()) 
    {
        JOptionPane.showMessageDialog(this, "Заполните все поля!");
        return;
    }

    try {
        double lowLim = Double.parseDouble(jTextFieldLow.getText());
        double upLim = Double.parseDouble(jTextFieldUp.getText());
        double step = Double.parseDouble(jTextFieldStep.getText());

        RecIntegral rec = new RecIntegral(lowLim, upLim, step);

        DefaultTableModel tModel = (DefaultTableModel) jTable1.getModel();
        tModel.addRow(new Object[]{lowLim, upLim, step, 0.0});

        arrInteg.add(rec);

        jTextFieldLow.setText("");
        jTextFieldUp.setText("");
        jTextFieldStep.setText("");

    } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(this, "Введите корректные числовые значения!"  );
    } catch (InvalidRec ex) {
        JOptionPane.showMessageDialog(this, ex.getMessage());
    } 
    }//GEN-LAST:event_jButtonAddActionPerformed

    private void jButtonResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResultActionPerformed
            try {
        DefaultTableModel tModel = (DefaultTableModel) jTable1.getModel();
        currentRow = jTable1.getSelectedRow();

        if (currentRow == -1) {
            JOptionPane.showMessageDialog(this, "Выберите строку!");
            return;
        }

        if (clients.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Нет подключённых клиентов!");
            return;
        }

        double low = Double.parseDouble(tModel.getValueAt(currentRow, 0).toString());
        double up = Double.parseDouble(tModel.getValueAt(currentRow, 1).toString());
        double step = Double.parseDouble(tModel.getValueAt(currentRow, 2).toString());

        int n = clients.size();
        expectedParts = n;       // сколько результатов ждём
        partialResults.clear();  // очищаем результаты

        double length = (up - low) / n;

        // отправляем задания клиентам
        for (int i = 0; i < n; i++) {
            double a = low + i * length;
            double b = (i == n - 1) ? up : a + length;

            String task = "TASK " + a + " " + b + " " + step;
            byte[] data = task.getBytes();

            DatagramPacket out = new DatagramPacket(
                    data, data.length,
                    clients.get(i).getAddress(),
                    clients.get(i).getPort()
            );

            serverSocket.send(out);
        }

        JOptionPane.showMessageDialog(this, "Задания отправлены клиентам!");

    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, "Ошибка: " + ex.getMessage());
    }

        

// TODO add your handling code here:
    }//GEN-LAST:event_jButtonResultActionPerformed

    private void formComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_formComponentHidden

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
                                      
    DefaultTableModel tModel = (DefaultTableModel) jTable1.getModel();
    int rowNum = jTable1.getSelectedRow();

    if (rowNum == -1) {
        JOptionPane.showMessageDialog(null, "Выберите строку!");
        return;
    }

    double low = Double.parseDouble(tModel.getValueAt(rowNum, 0).toString());
    double up = Double.parseDouble(tModel.getValueAt(rowNum, 1).toString());
    double step = Double.parseDouble(tModel.getValueAt(rowNum, 2).toString());

    for (int i = arrInteg.size() - 1; i >= 0; i--) {
        RecIntegral r = arrInteg.get(i);
        if (r.getLowLim() == low &&
            r.getUpLim() == up &&
            r.getStep() == step) 
        {
            arrInteg.remove(i);
            break;
        }
    }

    tModel.removeRow(rowNum);
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    private void DeleteAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteAllActionPerformed
       DefaultTableModel tModel = (DefaultTableModel) jTable1.getModel();
    tModel.setRowCount(0);
    }//GEN-LAST:event_DeleteAllActionPerformed

    private void AddColectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddColectionActionPerformed
       DefaultTableModel tModel = (DefaultTableModel) jTable1.getModel();
    tModel.setRowCount(0); 

    for (RecIntegral rec : arrInteg) {
        tModel.addRow(new Object[]{
            rec.getLowLim(),
            rec.getUpLim(),
            rec.getStep(),
            rec.geResult()
        });
    }
    }//GEN-LAST:event_AddColectionActionPerformed

    private void SaveTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveTextActionPerformed
                                         
    JFileChooser chooser = new JFileChooser();
    if (chooser.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) {
        try (FileWriter fw = new FileWriter(chooser.getSelectedFile())) {

            for (RecIntegral rec : arrInteg) {
                fw.write(rec.getLowLim() + " "
                        + rec.getUpLim() + " "
                        + rec.getStep() + " "
                        + rec.geResult() + "\n");
            }

            JOptionPane.showMessageDialog(this, "Файл успешно сохранён!");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Ошибка сохранения: " + ex.getMessage());
        }
    }
    }//GEN-LAST:event_SaveTextActionPerformed

    private void SaveBinaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveBinaryActionPerformed
       JFileChooser chooser = new JFileChooser();
    if (chooser.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) {
        try (ObjectOutputStream out = new ObjectOutputStream(
                new FileOutputStream(chooser.getSelectedFile()))) {

            out.writeObject(arrInteg);
            JOptionPane.showMessageDialog(this, "Данные сохранены (двоичный формат)");

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Ошибка сохранения: " + ex.getMessage());
        }
    }
    }//GEN-LAST:event_SaveBinaryActionPerformed

    private void DownloadTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DownloadTextActionPerformed
         JFileChooser chooser = new JFileChooser();
    if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {

        int choice = JOptionPane.showConfirmDialog(
                this,
                "Очистить исходную коллекцию?",
                "Подтверждение",
                JOptionPane.YES_NO_OPTION
        );

        if (choice == JOptionPane.YES_OPTION) {
            arrInteg.clear();
            ((DefaultTableModel) jTable1.getModel()).setRowCount(0);
        }

        try (BufferedReader br = new BufferedReader(new FileReader(chooser.getSelectedFile()))) {

            DefaultTableModel tModel = (DefaultTableModel) jTable1.getModel();

            String line;
            while ((line = br.readLine()) != null) {
                String[] p = line.split(" ");
                double low = Double.parseDouble(p[0]);
                double up = Double.parseDouble(p[1]);
                double step = Double.parseDouble(p[2]);
                double res = Double.parseDouble(p[3]);

                RecIntegral rec = new RecIntegral(low, up, step, res);
                arrInteg.add(rec);

                tModel.addRow(new Object[]{low, up, step, res});
            }

            JOptionPane.showMessageDialog(this, "Файл успешно загружен!");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Ошибка загрузки: " + ex.getMessage());
        }
    }
    }//GEN-LAST:event_DownloadTextActionPerformed

    private void DownloadBinaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DownloadBinaryActionPerformed
     JFileChooser chooser = new JFileChooser();
    if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {

        int choice = JOptionPane.showConfirmDialog(
                this,
                "Очистить исходную коллекцию?",
                "Подтверждение",
                JOptionPane.YES_NO_OPTION
        );

        if (choice == JOptionPane.YES_OPTION) {
            arrInteg.clear();
            ((DefaultTableModel) jTable1.getModel()).setRowCount(0);
        }

        try (ObjectInputStream in = new ObjectInputStream(
                new FileInputStream(chooser.getSelectedFile()))) {

            ArrayList<RecIntegral> loaded = (ArrayList<RecIntegral>) in.readObject();

            DefaultTableModel tModel = (DefaultTableModel) jTable1.getModel();

            for (RecIntegral rec : loaded) {
                arrInteg.add(rec);
                tModel.addRow(new Object[]{
                        rec.getLowLim(),
                        rec.getUpLim(),
                        rec.getStep(),
                        rec.geResult()
                });
            }

            JOptionPane.showMessageDialog(this, "Данные загружены (двоичный формат)");

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Ошибка загрузки: " + ex.getMessage());
        }
    }
    }//GEN-LAST:event_DownloadBinaryActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddColection;
    private javax.swing.JButton DeleteAll;
    private javax.swing.JButton DownloadBinary;
    private javax.swing.JButton DownloadText;
    private javax.swing.JButton SaveBinary;
    private javax.swing.JButton SaveText;
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonResult;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldLow;
    private javax.swing.JTextField jTextFieldStep;
    private javax.swing.JTextField jTextFieldUp;
    // End of variables declaration//GEN-END:variables
}
